version: '3.3'

services:
  bot:
    container_name: "tgbot_template_container"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/src"
    volumes:
    - ./app:/src
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    networks:
    - tgbot_template


networks:
  tgbot_template:
    driver: bridge
