version: '3.3'

services:
  bot:
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/src"
    volumes:
      - ./app:/src
    command: python3 -m bot
    restart: on-failure
    env_file:
      - ".env"
    depends_on:
      - db
      - redis
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_database
    volumes:
      - ./db_data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
    volumes:
      - ./redis_data:/data
    depends_on:
      - db
